# Generated by Django 4.2.25 on 2026-01-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_bookingdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='guestsc',
            field=models.IntegerField(),
        ),
    ]
